/**
 * Canonical action codes written to the Log collection.
 *
 * Previously these were free-text literals repeated across every service, which
 * meant the Audit Trail filter could silently miss entries after a typo. The
 * audit viewer filters on these values, so they must never be inlined again.
 */
export enum AuditAction {
  // Authentication
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
  ACCOUNT_SETUP_COMPLETED = "ACCOUNT_SETUP_COMPLETED",

  // User administration
  USER_INVITED = "USER_INVITED",
  USER_RE_INVITED = "USER_RE_INVITED",
  USER_UPDATED = "USER_UPDATED",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_REACTIVATED = "USER_REACTIVATED",
  USER_DELETED = "USER_DELETED",
  USER_SESSIONS_REVOKED = "USER_SESSIONS_REVOKED",
  PROFILE_UPDATED = "PROFILE_UPDATED",

  // Department administration
  DEPARTMENT_CREATED = "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED = "DEPARTMENT_UPDATED",
  DEPARTMENT_DELETED = "DEPARTMENT_DELETED",

  // Budget administration
  BUDGET_PERIOD_CREATED = "BUDGET_PERIOD_CREATED",
  BUDGET_PERIOD_UPDATED = "BUDGET_PERIOD_UPDATED",
  BUDGET_LOCKED = "BUDGET_LOCKED",
  BUDGET_UNLOCKED = "BUDGET_UNLOCKED",
  BUDGET_COMMITTED = "BUDGET_COMMITTED",
  BUDGET_OVERRUN = "BUDGET_OVERRUN",

  // Role administration
  ROLE_PERMISSIONS_UPDATED = "ROLE_PERMISSIONS_UPDATED",
  WORKFLOW_CONFIG_UPDATED = "WORKFLOW_CONFIG_UPDATED",

  // Expense lifecycle
  EXPENSE_CREATED = "EXPENSE_CREATED",
  EXPENSE_UPDATED = "EXPENSE_UPDATED",
  EXPENSE_SUBMITTED = "EXPENSE_SUBMITTED",
  EXPENSE_SUBMITTED_APPROVED_BUDGET = "EXPENSE_SUBMITTED_APPROVED_BUDGET",
  EXPENSE_STEP_APPROVED = "EXPENSE_STEP_APPROVED",
  EXPENSE_WORKFLOW_COMPLETED = "EXPENSE_WORKFLOW_COMPLETED",
  EXPENSE_REJECTED = "EXPENSE_REJECTED",
  EXPENSE_RETURNED = "EXPENSE_RETURNED",
  EXPENSE_CANCELLED = "EXPENSE_CANCELLED",
  EXPENSE_BANK_UPLOADED = "EXPENSE_BANK_UPLOADED",
  EXPENSE_CLOSED = "EXPENSE_CLOSED",
  PAYMENT_RELEASED = "PAYMENT_RELEASED",
  REQUEST_COMMENT_ADDED = "REQUEST_COMMENT_ADDED",
  ATTACHMENT_ADDED = "ATTACHMENT_ADDED",
  ATTACHMENT_REMOVED = "ATTACHMENT_REMOVED",

  // Exceptional budget path
  EXCEPTIONAL_BUDGET_APPROVED = "EXCEPTIONAL_BUDGET_APPROVED",
  EXCEPTIONAL_BUDGET_REJECTED = "EXCEPTIONAL_BUDGET_REJECTED",
  EXCEPTIONAL_BUDGET_RETURNED = "EXCEPTIONAL_BUDGET_RETURNED",

  // Infrastructure
  API_ROUTE_ERROR = "API_ROUTE_ERROR",
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
}
